---
- name: Converge
  hosts: all
  vars:
    filebeat_syslog_udp: true
    filebeat_syslog_tcp: true
  tasks:
    - name: "Include Elastics repos role"
      include_role:
        name: elastic-repos

    - name: "Include filebeat"
      include_role:
        name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
